# -*- coding: utf-8 -*-
"""apriori_algorithm.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fdR_DDdFXN-BNxIEL_1rAYGWrftMcQAS
"""

import seaborn as sns
import numpy as np
import pandas as pd
import os
import sys
from sklearn import datasets
import matplotlib.pyplot as plt
import collections 
from akapriori import apriori
# %matplotlib inline

def transaction(path1, path2, csv_column1, csv_column2, duplicate=True):
  df1=pd.read_csv(path1)
  df2=pd.read_csv(path2)
  # df=df.drop('Unnamed: 0', axis=1)
  df=pd.concat([df1, df2])
  df=df.fillna(0)
  
  print(df.shape) # (6644398, 6)
  
  dics = {}
  for i,v in df.iterrows():
    dics.setdefault(v[csv_column1], []).append(v[csv_column2])
  if duplicate:
    transaction = [i for i in dics.values()]
  else:
    transaction = [set(i) for i in dics.values()]
  return transaction



def Apriori(transaction, support=0.07, confidence=0.5, lift=1):
  rules1 = apriori(transaction, support=support, confidence=confidence, lift=lift)
  rules_sorted1 = sorted(rules1, key=lambda x: (x[4], x[3], x[2]), reverse=True) # ORDER BY lift DESC, confidence DESC, support DESC
  for r in rules_sorted1:
    print(r)
    
    

# example 1
transac = transaction('tra1.csv', 'tra2.csv', 'kaiin_id', 'cate_name')
Apriori(transac)

# example 2
transac2 = transaction('tra1.csv', 'tra2.csv', 'kaiin_id', 'brand_name', duplicate=None)
Apriori(transac2)